### ISSUE TITLE
[BUG] "Open in ..." button not working for opening in Ingress Intel or Google Maps

### ISSUE THREAD

**Issue by lollercopter** [MrJPGames/WayFarerPlus#195]
**Describe the bug**
The "Open in ..." button does nothing right now when reviewing new submissions or submission edits. It used to allow the user to see the submission's location in the Ingress Intel map or Google Maps.

**Comment by MrJPGames** [comment]
Thanks for your report, this bug has already been fixed in 67d4644813b5f6f31d2d6e0204ef13e04a74a02b

The update with the fix will go live for your platform (Firefox) in a few hours :)

**Comment by lollercopter** [comment]
I am running 1.14.10, which is the latest version reported in the changelog. Unless the changelog wasn't updated, the bug is still there in Firefox with 1.14.10.

**Comment by MrJPGames** [comment]
As I said the update with the fix wil go live in a few hours, the version will be 1.14.10.1

**Comment by crismorais** [comment]
> 1.14.10.1

I'm using version 1.14.10.1 in chrome and still have problems with maps and no options for Review using the keyboard.

**Comment by ultragreg** [comment]
There is no more Open In Button in the nomination page since 1.14.11.2
